### ISSUE TITLE
feat: "why choose us" section

### ISSUE THREAD

**Issue by 0xneves** [w3b3d3v/web3task-lp#14]
### Proposed Feature

Develop the following components for the second section of the Landing Page following the [Figma Design](https://www.figma.com/community/file/1335063165996522243/web3task):

![image](https://github.com/w3b3d3v/web3task-lp/assets/90667119/e1572313-a042-45bc-ad56-f0486f1db38c)

**Comment by heronlancellot** [comment]
Closed by #24
