### ISSUE TITLE
feat: metrics section

### ISSUE THREAD

**Issue by 0xneves** [w3b3d3v/web3task-lp#15]
### Proposed Feature

Create the metrics of the dApp, the third section of the landing page following the [Figma design](https://www.figma.com/community/file/1335063165996522243/web3task):

![image](https://github.com/w3b3d3v/web3task-lp/assets/90667119/9445efb2-0ac9-4ca9-ad92-729c5e40dbb0)

**Comment by Hardsys-Andre** [comment]
I want to take on this task

**Comment by Hardsys-Andre** [comment]
I've already started it

**Comment by heronlancellot** [comment]
Hey yo @Hardsys-Andre ! Assigned to you

**Comment by Hardsys-Andre** [comment]
The Card Stats creation task has been completed, follow the link below the PR.

https://github.com/w3b3d3v/web3task-lp/pull/27

**Comment by Guboehm** [comment]
@Hardsys-Andre @heronlancellot thanks for the work
