### ISSUE TITLE
feat: how it works section

### ISSUE THREAD

**Issue by 0xneves** [w3b3d3v/web3task-lp#16]
### Feature Proposal

Develop the "How it works", the fourth section of the landing page following the [Figma design](https://www.figma.com/community/file/1335063165996522243):

![image](https://github.com/w3b3d3v/web3task-lp/assets/90667119/18a066fb-d6b8-4b1a-aa38-c510a1ee3727)

**Comment by heronlancellot** [comment]
Closed by #25
