### ISSUE TITLE
feat: roadmap section

### ISSUE THREAD

**Issue by 0xneves** [w3b3d3v/web3task-lp#18]
### Feature Proposal

Create the roadmap section as the fifth section of the landing page following the [Figma design](https://www.figma.com/community/file/1335063165996522243):

The roadmap is just an image so it won't be too difficult. The issue #17 will provide the material for the mobile version.

![image](https://github.com/w3b3d3v/web3task-lp/assets/90667119/b60f3615-8974-4ce4-9fd7-0628ece3dfc1)

**Comment by heronlancellot** [comment]
Closed by #26
