### ISSUE TITLE
feat: FAQ section

### ISSUE THREAD

**Issue by 0xneves** [w3b3d3v/web3task-lp#19]
### Feature Proposal

Create the FAQ as the sixth section on the landing page following the [Figma design](https://www.figma.com/community/file/1335063165996522243). The FAQ content was defined in [this issue](https://github.com/w3b3d3v/web3task-org/issues/20#issuecomment-1850420189).

![image](https://github.com/w3b3d3v/web3task-lp/assets/90667119/4706b842-8293-4bf1-9230-08d4f7d9be3f)

**Comment by Guboehm** [comment]
Under development

**Comment by Guboehm** [comment]
Issue resolved: https://github.com/w3b3d3v/web3task-lp/pull/34
