### ISSUE TITLE
feat: call to action section

### ISSUE THREAD

**Issue by 0xneves** [w3b3d3v/web3task-lp#20]
### Feature Proposal

Create the "Call to action" as the seventh section of the landing page following the [Figma design](https://www.figma.com/community/file/1335063165996522243):

![image](https://github.com/w3b3d3v/web3task-lp/assets/90667119/0504371d-145d-4fc3-85fd-55ffc63bcabd)

**Comment by Hardsys-Andre** [comment]
I want to take on this task

**Comment by heronlancellot** [comment]
> I want to take on this task

hey yo @Hardsys-Andre ! Assigned to you 🚀

**Comment by Hardsys-Andre** [comment]
hey @heronlancellot, I did the PR for issue #20, waiting for a response, follow the link below:
https://github.com/w3b3d3v/web3task-lp/pull/28

**Comment by heronlancellot** [comment]
> hey @heronlancellot, I did the PR for issue #20, waiting for a response, follow the link below: #28

hey yo @Hardsys-Andre  ! Perfect

**Comment by Guboehm** [comment]
task under review, will be updated during the week

**Comment by heronlancellot** [comment]
Closed by #28
