### ISSUE TITLE
feat: footer section

### ISSUE THREAD

**Issue by 0xneves** [w3b3d3v/web3task-lp#21]
### Feature Proposal

Create the Footer as the eight and last section of the landing page following the [Figma design](https://www.figma.com/community/file/1335063165996522243):

![image](https://github.com/w3b3d3v/web3task-lp/assets/90667119/5b5df69d-7b44-40cd-9aa8-ce9a9bf23f4b)

**Comment by Hardsys-Andre** [comment]
Hey @heronlancellot, I want to take on this task

**Comment by heronlancellot** [comment]
> Hey [@heronlancellot](https://github.com/heronlancellot), I want to take on this task

hey yo @Hardsys-Andre ! It's all yours! 
assigned to you

**Comment by Guboehm** [comment]
In development, will be updated during the week

**Comment by Hardsys-Andre** [comment]
@heronlancellot, sent the PR for analysis, follow the link below:
https://github.com/w3b3d3v/web3task-lp/pull/29

**Comment by heronlancellot** [comment]
Closed by #29
