### ISSUE TITLE
feat: carrousel for partners logos

### ISSUE THREAD

**Issue by 0xneves** [w3b3d3v/web3task-lp#22]
### Feature Proposal

The current frame is static on the desktop and is pilled up in the mobile version:

![image](https://github.com/w3b3d3v/web3task-lp/assets/90667119/90501924-36e6-488d-987a-bf7408864bb8)

### Preferred Solution

 - [ ] Create a horizontal carrousel for the sponsors and partners, showcasing them with motion
 - [ ] Adapt to the mobile version as well

**Comment by Hardsys-Andre** [comment]
hello @heronlancellot, Give me this issue please, I've already started it

**Comment by heronlancellot** [comment]
> hello @heronlancellot, Give me this issue please, I've already started it

hey yo @Hardsys-Andre ! Perfect ! Assigned to you

**Comment by Hardsys-Andre** [comment]
The changes have been made, a mobile-responsive carousel has been created.
Follow the PR link below:
https://github.com/w3b3d3v/web3task-lp/pull/31

**Comment by Guboehm** [comment]
@heronlancellot Can you review the PR, please ?

**Comment by Guboehm** [comment]
@Hardsys-Andre Is it possible to implement the movement feature ?

**Comment by Hardsys-Andre** [comment]
@Guboehm, task completed and merged, you can now consider it completed.
