### ISSUE TITLE
feat: Dapp link action

### ISSUE THREAD

**Issue by Guboehm** [w3b3d3v/web3task-lp#32]
### Feature Proposal

It is necessary to implement the action of the buttons that route to the dapp.
There are 3 buttons on the landing page that need to be targeted.
The redirect link is: https://web3task.w3d.community/

Button 1:
<img width="1146" alt="Captura de Tela 2024-04-11 às 22 00 48" src="https://github.com/w3b3d3v/web3task-lp/assets/32460314/158ae447-36ce-4c40-91c0-c4170f6fedec">

Button 2:
<img width="615" alt="Captura de Tela 2024-04-11 às 22 02 42" src="https://github.com/w3b3d3v/web3task-lp/assets/32460314/48897b57-38d6-455a-b8f0-8131376735fb">

Button 3:
<img width="606" alt="Captura de Tela 2024-04-11 às 22 04 24" src="https://github.com/w3b3d3v/web3task-lp/assets/32460314/9687bae3-cd82-4f55-b09f-58b99e8430c6">

**Comment by Hardsys-Andre** [comment]
@Guboehm

**Comment by Hardsys-Andre** [comment]
@Guboehm hello, I have already inserted the links in the dApp buttons and adjusted the first button in the header by inserting the arrow inside the button.

**Comment by Guboehm** [comment]
Nice, we are looking forward to the pull request.
