### ISSUE TITLE
feat: Menu actions

### ISSUE THREAD

**Issue by Guboehm** [w3b3d3v/web3task-lp#33]
### Feature Proposal

Link buttons to page sections.
The expected behavior is that clicking will scroll to the selected section.

<img width="437" alt="Captura de Tela 2024-04-11 às 22 10 47" src="https://github.com/w3b3d3v/web3task-lp/assets/32460314/41d86e0a-d7b6-429e-b37a-114898d94fca">

**Comment by Hardsys-Andre** [comment]
@Guboehm

**Comment by Hardsys-Andre** [comment]
@Guboehm hello, I already inserted the links in the items that were already ready, I also talked to Heron and requested the branch that contains the missing items to complete the Landing page and thus finish all the links.

**Comment by Guboehm** [comment]
Nice, we are looking forward to the pull request.
