### ISSUE TITLE
feat: Roadmap section

### ISSUE THREAD

**Issue by Guboehm** [w3b3d3v/web3task-lp#35]
### Feature Proposal

Create the Roadmap section on the landing page following the [Figma design](https://www.figma.com/community/file/1335063165996522243).

<img width="218" alt="Captura de Tela 2024-05-02 às 22 05 26" src="https://github.com/w3b3d3v/web3task-lp/assets/32460314/96d0937b-03ec-4477-8dd3-18494d081664">

**Comment by Hardsys-Andre** [comment]
Hello @Guboehm

**Comment by Guboehm** [comment]
I'm assigning to you @Hardsys-Andre

**Comment by Hardsys-Andre** [comment]
@Guboehm,  done the PR of the Roadmap Section, check that everything is in order, including the mobile version.

Follow the PR link; https://github.com/w3b3d3v/web3task-lp/pull/37
