### ISSUE TITLE
Improvement: Transition effects in some components

### ISSUE THREAD

**Issue by Guboehm** [w3b3d3v/web3task-lp#40]
### Feature Proposal
[Hardsys-Andre](https://github.com/Hardsys-Andre) made animation improvements to some components.
The changes are in following pr: #38

**Comment by Hardsys-Andre** [comment]
@Guboehm

**Comment by Guboehm** [comment]
@Hardsys-Andre Thanks for this contribution.

**Comment by Guboehm** [comment]
@Hardsys-Andre Same adjusts
1 - Remove WEB3TASK text on the top and change image to our logo.
2 - Fix button click in lets starting build section.
