### ISSUE TITLE
feat: header for landing page

### ISSUE THREAD

**Issue by 0xneves** [w3b3d3v/web3task-lp#6]
### Feature Request:

We want the following header for the landing page:

![image](https://github.com/w3b3d3v/web3task-lp/assets/90667119/9894ac9e-b0e9-4726-959f-ad97c57011b9)

Realize we want margins on both sides since all components on the rest of the application will follow the vertical alignment. This is not a strict rule for now but to be applicable during the rest of the development and optimization phase.

There is a total of 1 component and 3 organisms within the header, they are specified below:

![image](https://github.com/w3b3d3v/web3task-lp/assets/90667119/e7c8612f-0736-4da2-a5ca-e46d48f33f99)

Requirements for the header:
- Logo
- Menu
- - Home
- - How it works
- - Roadmap
- - FAQs
- dApp button

### Design reference:

This Figma is open for inspection in [this link.](https://www.figma.com/community/file/1335063165996522243)
Please follow the design with fidelity.

### Additional context:

No need for links or outbound links. This is purely CSS - visualization.

**Comment by andressa-cabral** [comment]
https://www.figma.com/file/UDGGqo8K53CiYYpGutoVuH/PodLabs?type=design&node-id=1527-1886&mode=design&t=zIOQZlNBE9TUVPIy-0

**Comment by heronlancellot** [comment]
Closed by #7
